from webapp.views.announcement import AnnouncementListView, AnnouncementCreateView, AnnouncementUpdateView, AnnouncementDetailView, announcement_delete_view
from webapp.views.moderatoring import ModeratoringListView
from webapp.views.comment import CommentCreateView