# Generated by Django 3.2.6 on 2021-08-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210821_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='announcement_pics'),
        ),
    ]
