# Generated by Django 3.2.6 on 2021-08-21 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210821_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='moderate_rejected',
        ),
    ]
