# Generated by Django 3.2.6 on 2021-08-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_announcement_moderate_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'permissions': [('moderator', 'Модератор')], 'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
    ]
