# Generated by Django 3.2.6 on 2021-08-21 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_announcement_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5)])),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='webapp.announcement')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'Comments',
            },
        ),
    ]
